/**@author MK MMADI 221052648
  *@see FireDisplay : a related class
  *
  */
import acsse.csc2a.fmb.FireworkDisplay;

import java.io.Console;
import java.io.IOException;
import java.util.Scanner;

public class Main {
	public static void main(String[] args)
	{
		FireworkDisplay Display1 = new FireworkDisplay();
		FireworkDisplay Display2 = new FireworkDisplay();
		boolean blnContinue=true;
		
		InitialiseDisplay1(Display1);
		InitialiseDisplay2(Display2);
		
		do
		{
			Scanner in = new Scanner(System.in);
			int intChoice = 0;
			
			clearScreen();
			System.out.println("Choose a Firework Display(Enter a number 1 or 2) : ");
			System.out.println("1. Display 1 (Alpha)");
			System.out.println("2. Display 2 (Omega)");
			System.out.println("3. Exit Program.");
			intChoice=in.nextInt();
			
			switch(intChoice)
			{
			case 1:
			{
				Display1.printDisplay();
				System.out.println("Enter any key to continiue");
				new Scanner(System.in).nextLine();
				break;
			}
			
			case 2:
			{
				Display2.printDisplay();
				System.out.println("Enter any key to continiue");
				new Scanner(System.in).nextLine();
				break;
			}
			
			default :
			{
				System.exit(0);
				System.out.println("Enter any key to continiue");
				new Scanner(System.in).nextLine();
			}
			}
		}while(blnContinue);
		

	}
	public static void InitialiseDisplay1(FireworkDisplay Display1)
	{
		Display1.setDisplay_Name("FireWorkUltra");
		Display1.setDiplay_Theme("New Year");
		Display1.setDisplay_ID("DS-Ultra");
		Display1.setLead_Technician("Charles Monroe", "011 574 6354");
		String Firework_ID="FW_001";
		String Firework_Name="The Awe";
		double Firework_Fuse_Length=10.00;
		int intColour=1;
		Display1.setFireWorks(Firework_ID,Firework_Name,Firework_Fuse_Length,intColour);
	}
	
	public static void InitialiseDisplay2(FireworkDisplay Display2)
	{
		Display2.setDisplay_Name("FireWorkOmega");
		Display2.setDiplay_Theme("Chinise New Year");
		Display2.setDisplay_ID("DS-Omega");
		Display2.setLead_Technician("Sandile Morena", "011 54 2648");
		String Firework_ID="FW_002";
		String Firework_Name="The Boom";
		double Firework_Fuse_Length=10.00;
		int intColour=6;
		Display2.setFireWorks(Firework_ID,Firework_Name,Firework_Fuse_Length,intColour);
	}

	
	
	/*Generated by MS-Copilot */
	public static void clearScreen() {
		//Don`t know what this means but it works.Sooo yeahhhh ... :).
		try {
		    new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();
		} catch (IOException | InterruptedException e) {
		    System.out.println(e);
		}

	}

}
