/**@author MK MMADI 221052648
  *@see FireDisplay : a related class
  *
  */
import acsse.csc2a.fmb.FireworkDisplay;

import java.io.Console;
import java.io.IOException;
import java.util.Scanner;

public class Main {
	public static void main(String[] args)
	{
		FireworkDisplay Display1 = new FireworkDisplay();
		FireworkDisplay Display2 = new FireworkDisplay();
		boolean blnContinue=true;
		
		InitialiseDisplay1(Display1);
		InitialiseDisplay2(Display2);
		
		do
		{
			Scanner in = new Scanner(System.in);
			int intChoice = 0;
			
			clearScreen();
			System.out.println("Choose a Firework Display(Enter a number 1 or 2) : ");
			System.out.println("1. Display 1 (Alpha)");
			System.out.println("2. Display 2 (Omega)");
			System.out.println("3. Exit Program.");
			intChoice=in.nextInt();
			
			switch(intChoice)
			{
			case 1:
			{
				Display_Display1(Display1);
				System.out.println("Enter any key to continiue");
				new Scanner(System.in).nextLine();
				break;
			}
			
			case 2:
			{
				Display_Display2(Display2);
				System.out.println("Enter any key to continiue");
				new Scanner(System.in).nextLine();
				break;
			}
			
			case 3:
			{
				System.exit(0);
				System.out.println("Enter any key to continiue");
				new Scanner(System.in).nextLine();
			}
			}
		}while(blnContinue);
		

	}
	public static void InitialiseDisplay1(FireworkDisplay Display1)
	{
		Display1.setDisplay_Name("FireWorkUltra");
		Display1.setDiplay_Theme("New Year");
		Display1.setDisplay_ID("FW-Ultra");
		Display1.setLead_Technician("Charles Monroe", "011 574 6354");
	}
	
	public static void InitialiseDisplay2(FireworkDisplay Display2)
	{
		Display2.setDisplay_Name("FireWorkOmega");
		Display2.setDiplay_Theme("Chinise New Year");
		Display2.setDisplay_ID("FW-Omega");
		Display2.setLead_Technician("Sandile Morena", "011 54 2648");
	}

	public static void Display_Display1(FireworkDisplay Display1)
	{
		System.out.format("%-20s %-20s %-20s %-30s %-20s\n", "Display Name", "Display ID", "Display Theme", "Lead Technician Name And Surname", "Lead Technician Phone Number");
	    System.out.format("%-20s %-20s %-20s %-40s %-60s\n", Display1.getDisplay_Name(), Display1.getDisplay_ID(), Display1.getDisplayTheme(), Display1.getLead_Technician_Name(), Display1.getLead_Technician_PhoneNumber());

	}
	
	public static void Display_Display2(FireworkDisplay Display2)
	{
		System.out.format("%-20s %-20s %-20s %-30s %-20s\n", "Display Name", "Display ID", "Display Theme", "Lead Technician Name And Surname", "Lead Technician Phone Number");
	    System.out.format("%-20s %-20s %-20s %-40s %-60s\n", Display2.getDisplay_Name(), Display2.getDisplay_ID(), Display2.getDisplayTheme(), Display2.getLead_Technician_Name(), Display2.getLead_Technician_PhoneNumber());


	}
	
	/*Generated by MS-Copilot */
	public static void clearScreen() {
		//Don`t know what this means but it works.Sooo yeahhhh ... :).
		try {
		    new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();
		} catch (IOException | InterruptedException e) {
		    System.out.println(e);
		}

	}

}
